# Generated by Django 5.0.4 on 2024-06-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name_plural': 'UserLibraries'},
        ),
    ]
